name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew app:assembleRelease
    # step：向蒲公英上传文件
    - name: Upload To Pgyer
      uses: JantHsueh/upload-file-action@master
      with:
        url: https://www.pgyer.com/apiv2/app/upload
        method: POST
        forms: '{"_api_key":"${{ secrets.PGYER_API_KEY }}","buildInstallType":1}'
        fileForms: '{"file":"${{ github.workspace }}/app/build/outputs/apk/release/*.apk"}'
    - name: Upload apk to artifact
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: lottery_app
        path: ${{ github.workspace }}/app/build/outputs/apk/release/*.apk